variables:
  PACKAGE_REPO_URL: "http://packages.opentap.io"

stages:
  - build
  - test
  - package
  - deploy
  - docker

#############################################
# Stage: build                              #
#############################################

# Build this in the "build" stage because it cannot be parallelized with the "Documentation" build
Build-DevGuide:
  stage: build
  image: registry.gitlab.com/opentap/buildrunners/documentationgeneration:latest
  tags: [ docker, gce ]
  script: |
           tap generate-pdf "doc/Developer Guide/Readme.md" --appendix "Appendix C: Migration Guide"="doc/Migration/Migrating from tap 8 to 9/Readme.md" --toc --skip-first-file --out "sdk/Examples/OpenTAP Developer Guide.pdf" --frontpage "doc/Developer Guide/Frontpage.html" --frontpage-file "doc/Developer Guide/Frontpage.png" --notices "doc/Developer Guide/Introduction/Notices.md"
  artifacts:
    expire_in: 1 week
    paths:
       - sdk/Examples/OpenTAP Developer Guide.pdf

Doc-API:
  stage: build
  image: registry.gitlab.com/opentap/buildrunners/doxygen:latest
  tags: [ docker, gce ]
  script: 
         - mkdir Help
         - mkdir API
         - rootdir=`pwd`
         - cd "doc/API Documentation"
         - doxygen Doxyfile
         - cd "apiref/html"
         - chmcmd index.hhp
         - cp OpenTapApiReference.chm $rootdir/Help/
         - cp -r . $rootdir/API/
  artifacts:
    expire_in: 1 week
    paths:
       - Help/OpenTapApiReference.chm
       - API

Build-Linux64:
  stage: build
  image: microsoft/dotnet:2.1-sdk-stretch
  tags: [ docker, gce ]
  script: 
         - dotnet publish -c NetCore -r linux-x64 OpenTAP.sln
         - dotnet publish -c NetCore -r linux-x64 tap/tap.csproj
  artifacts:
    expire_in: 1 week
    paths:
       - bin/Release/linux-x64/publish

# Builds the Everything.sln solution
Build-x86:
  stage: build
  image: mcr.microsoft.com/dotnet/framework/sdk:4.7.2
  tags: [ docker, windows ]
  script:
         - MSBuild OpenTAP.sln /t:restore /p:Configuration=Release /p:Platform=x86 /target:Rebuild /p:DefineConstants="TRACE" /m
         - dotnet restore -r win7-x86
         - MSBuild OpenTAP.sln /p:Configuration=Release /p:Platform=x86 /target:Rebuild /p:DefineConstants="TRACE" /m
         - dotnet build tap\tap.csproj -c Release -r win-x86
         - Remove-Item -recurse "bin\Release\Packages"
  artifacts:
    expire_in: 1 week
    paths:
       - bin/Release/

Build-x64:
  stage: build
  image: mcr.microsoft.com/dotnet/framework/sdk:4.7.2
  tags: [ docker, windows ]
  script: 
         - MSBuild /t:restore OpenTAP.sln /p:Configuration=Release /p:Platform=x64 /target:Rebuild /p:DefineConstants="TRACE" /m
         - dotnet restore -r win7-x64
         - MSBuild OpenTAP.sln /p:Configuration=Release /p:Platform=x64 /target:Rebuild /p:DefineConstants="TRACE" /m
         - dotnet build tap\tap.csproj -c Release -r win-x64
         - Remove-Item -recurse "bin\Release\Packages"
         - Move-Item bin\Release bin\Release64
  artifacts:
    expire_in: 1 week
    paths:
       - bin/Release64/

WarningTest:
  stage: build
  image: mcr.microsoft.com/dotnet/framework/sdk:4.7.2
  tags: [ docker, windows ]
  script: 
         - MSBuild OpenTAP.sln /t:restore /p:Configuration=Release /p:Platform=x86 /target:Rebuild /p:DefineConstants="TRACE" /p:TreatWarningsAsErrors="true" /m
         - MSBuild OpenTAP.sln /p:Configuration=Release /p:Platform=x86 /target:Rebuild /p:DefineConstants="TRACE" /p:TreatWarningsAsErrors="true" /m


# #############################################
# # Stage: test                               #
# #############################################

# Gets bin directory from the builddrop location and runs unit tests in Tap.Engine.dll
TestEngine:
  stage: test
  image: mcr.microsoft.com/dotnet/framework/sdk:4.7.2
  tags: [ docker, windows ]
  dependencies:
     - Build-x86
  script:
         - MSBuild OpenTAP.sln /t:restore /p:Configuration=Release /p:Platform=x86 /target:Rebuild /p:DefineConstants="TRACE" /m
         - packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe bin/Release/OpenTap.UnitTests.dll --labels=All
  artifacts:
    when: always
    expire_in: 1 week
    paths:
       - "TestResult.xml"

# Can't run on docker, as a unit test is using dotfuscator
TestPackage:
  stage: test
  image: mcr.microsoft.com/dotnet/framework/sdk:4.7.2
  tags: [ docker, windows ]
  dependencies:
     - Build-x86
  script:
         - copy-item -r "Package.UnitTests/Packages" bin/Release
         - MSBuild OpenTAP.sln /t:restore /p:Configuration=Release /p:Platform=x86 /target:Rebuild /p:DefineConstants="TRACE" /m
         - packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe bin/Release/OpenTap.Package.UnitTests.dll --labels=All
  artifacts:
    when: always
    expire_in: 1 week
    paths:
       - "TestResult.xml"

.LinuxScript:
  tags: [ docker, gce ]
  dependencies:
     - Build-Linux64
  script:
        - cp -r Engine.UnitTests/TestTestPlans bin/Release/linux-x64/publish
        - cd bin/Release/linux-x64/publish
        - chmod +x tap
        - echo "./tap run -v TestTestPlans/testMultiReferencePlan.TapPlan; if [ \$? -eq 20 ]; then echo \"OK\"; else false; fi" >./run_ubuntu_test.sh
        - chmod +x ./run_ubuntu_test.sh
        - bash run_ubuntu_test.sh

TestUbuntu:
  stage: test
  image: microsoft/dotnet:2.1-sdk-stretch
  extends: .LinuxScript

TestCentos7:
  stage: test
  image: 
    name: stefanholst0/dotnet-21-centos7-root:latest
    entrypoint: [ "" ]
  extends: .LinuxScript

# TestUbuntuPackaged:
#   image: buildpack-deps:bionic
#   tags: [docker, ubuntu18.4]
#   stage: test
#   dependencies:
#      - Package-BaseUbuntu
#   script:
#      - DEST_DIR=testInstallDir
#      - mkdir $DEST_DIR
#      - unzip TAPLinux.TapPackage -d $DEST_DIR
#      - chmod -R +w $DEST_DIR
#      - chmod +x $DEST_DIR/tap
#      - cp -r opentap/Engine.UnitTests/TestTestPlans $DEST_DIR
#      - cp bin/linux-x64/publish/OpenTap.UnitTests.dll $DEST_DIR
#      - cd $DEST_DIR
#      - echo "./tap run -v TestTestPlans/testMultiReferencePlan.TapPlan
#  if [ \$? -eq 20 ]
#  then echo \"OK\"
#  else false
#  fi" >./run_ubuntu_test.sh
#      - bash run_ubuntu_test.sh

# OverrideConfig:
#   stage: test
#   dependencies: []
#   script: |
#           if not exist "bin/Release" mkdir "bin/Release"
#           echo Compression=none > "bin/Release/compression.iss"
#   except:
#     - /^integration$/
#     - /^release[0-9]+x$/
#     - /^ship[0-9]+x$/
#     - /^rc[0-9]+x$/
#   artifacts:
#     when: on_success
#     expire_in: 7 day
#     paths:
#        - "bin/Release/compression.iss"


#############################################
# Stage: package                            #
#############################################

Package-Windows:
  stage: package
  image: registry.gitlab.com/opentap/buildrunners/signrunner:latest
  tags: [ docker, windows ]
  only:
    - tags
    - /^release.*$/
    - master
  dependencies:
     - Build-x64
     - Doc-API
  script:
         - nuget restore OpenTAP.sln
         - cd bin/Release64
         - .\tap.exe package install -f "/repo/Sign.TapPackage"
         - cmd /C ".\tap.exe package create -v ../../opentapCE.package.xml -o Packages/OpenTAP/OpenTAP.Windows.TapPackage --install"
         - copy-item Packages/OpenTAP/OpenTAP.Windows.TapPackage OpenTAP.Windows.TapPackage
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
       - OpenTAP.Windows.TapPackage

Package-Linux:
  stage: package
  image: registry.gitlab.com/opentap/buildrunners/signrunner:latest
  tags: [ docker, windows ]
  only:
    - tags
    - /^release.*$/
    - master
  dependencies:
     - Build-x86
     - Build-Linux64
  script:
         -  mv bin\Release\linux-x64 bin\linux-x64
         -  pushd bin\linux-x64\publish
         -  ../../Release/tap package download --os Linux --architecture x64 -f -r $env:PACKAGE_REPO_URL -t . Demonstration
         -  mv "Demonstration*.TapPackage" "Demonstration.TapPackage"
         -  ../../Release/tap package install -f "/repo/Sign.TapPackage"
         -  cmd /C "..\..\Release\tap package create -v ../../../opentap_linux64.package.xml -o Packages/OpenTAP.Linux.TapPackage --install"
         -  cp Packages/OpenTAP.Linux.TapPackage ../../../OpenTAP.Linux.TapPackage
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
       - OpenTAP.Linux.TapPackage


# #############################################
# # Stage: deploy                             #
# #############################################

Installer-Windows:
  stage: deploy
  image: registry.gitlab.com/opentap/buildrunners/inno
  tags: [ docker, windows ]
  only:
    - tags
    - /^release.*$/
    - master
  dependencies:
     - Build-x64
     - Package-Windows
  script:
         - pushd bin\Release64
         - $version = ./tap.exe sdk gitversion
         - echo "OpenTAP.$($version).exe"

         - ./tap.exe package install -f -v "/BundleInstaller.TapPackage"
         - Remove-Item "Packages\Bundle Installer\Assets\LICENSES.txt"

         - ./tap.exe sdk create-bundle --sign "Keysight Technologies, Inc" --no-gui --tap64 "Packages/OpenTAP/OpenTAP.Windows.TapPackage" -x ../../Installer/Assets/opentapCE.installer.xml setup.exe
         - Move-Item setup.exe ..\..\OpenTAP.$($version).exe
  artifacts:
    expire_in: 1 week
    paths:
       - "*.exe"

Installer-Linux:
  stage: deploy
  image: mcr.microsoft.com/dotnet/framework/sdk:4.7.2
  tags: [ docker, windows ]
  only:
    - tags
    - /^release.*$/
    - master
  dependencies:
     - Package-Linux
  script:
         - Invoke-WebRequest https://netcologne.dl.sourceforge.net/project/gnuwin32/tar/1.13-1/tar-1.13-1-bin.exe -Outfile tarsetup.exe
         - Start-process .\tarsetup.exe -NoNewWindow -Wait -ArgumentList "/SILENT"

         - $path=(get-item -path "./").Fullname
         - $str=[IO.File]::ReadAllText($path + "/LinuxInstructions/INSTALL.sh") -replace "`r`n", "`n"
         - ([IO.File]::WriteAllText($path + "/INSTALL.sh", $str))

         - $str=[IO.File]::ReadAllText($path + "/LinuxInstructions/README") -replace "`r`n", "`n"
         - ([IO.File]::WriteAllText($path + "/README", $str))

         - cmd /C '"C:\Program Files (x86)\GnuWin32\bin\tar.exe" -cf "OpenTAP.tar" OpenTAP.Linux.TapPackage INSTALL.sh README'
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
       - "OpenTAP.tar"


# #############################################
# # Stage: docker                             #
# #############################################
.DockerLinuxBuild:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies:
     - Installer-Linux
  stage: docker
  tags: [ docker, gce ]
  script:
        - mv OpenTAP.Linux.TapPackage docker/Linux/OpenTAP.Linux.TapPackage
        - cd docker/Linux
        - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKER_USER\", \"password\":\"$DOCKER_PASS\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context=$CI_PROJECT_DIR/docker/Linux --dockerfile=Dockerfile --destination=opentapio/opentap:$version-ubuntu18.04

DockerLinux-Release:
  extends: .DockerLinuxBuild
  only:
    - tags
  before_script:
        - version=$(cat .gitversion | sed -nr 's/version *= *([0-9]+\.[0-9]+)\.[0-9]+/\1/p')

DockerLinux-RC:
  extends: .DockerLinuxBuild
  only:
    - /^release.*$/
  before_script:
        - version=rc

DockerLinux-Beta:
  extends: .DockerLinuxBuild
  only:
    - master
  before_script:
        - version=beta

.DockerWindowsBuild:
  stage: docker
  tags:
    - docker-build,windows,1809
  dependencies:
     - Installer-Windows
  script:
        - copy-item OpenTAP.*.exe docker/Windows/OpenTAP.exe
        - cd docker/Windows
        - docker login -u $env:DOCKER_USER -p $env:DOCKER_PASS
        - docker build -t opentapio/opentap:$env:version-windowsserver1809 .
        - docker push opentapio/opentap:$env:version-windowsserver1809
        - docker logout

DockerWindows-Release:
  extends: .DockerWindowsBuild
  only:
    - tags
  before_script:
        - $match = cat .\.gitversion | select-string 'version *= *([0-9]+\.[0-9]+)\.[0-9]+'
        - $env:version=$match.Matches.Groups[1].Value
        - echo $env:version

DockerWindows-rc:
  extends: .DockerWindowsBuild
  only:
    - /^release.*$/
  before_script:
        - $env:version="rc"

DockerWindows-beta:
  extends: .DockerWindowsBuild
  only:
    - master
  before_script:
        - $env:version="beta"
