#!/bin/bash
TAP_VERSION=9.4.2 # semver
rm -rf ./OpenTAP
mkdir -p OpenTAP/DEBIAN
mkdir -p OpenTAP/usr/bin
mkdir -p OpenTAP/usr/share/tap
mkdir -p OpenTAP/var/log/SessionLogs

unzip ./OpenTAP*.TapPackage -d OpenTAP/usr/share/tap

pushd OpenTAP/usr/share/tap
ln -s ../../../var/log/SessionLogs
popd
pushd OpenTAP/usr/bin 
ln -s ../share/tap/tap
popd

BYTES=$(du -sb OpenTAP | cut -f1)
DIVISOR=1024
KBYTES=$((BYTES / DIVISOR))

sed control-debian -e "s/@TAP_VERSION@/$TAP_VERSION/g" -e "s/@INSTALLED_SIZE@/$KBYTES/g" > OpenTAP/DEBIAN/control