#!/bin/bash
# Exit on error
set -e

GIT_ROOT="$(git rev-parse --show-toplevel)"
# got an exception from an external library when running tap sdk gitversion locally. fix in the future so we can host alpha- and beta builds as well
# VERSION=$(cat "$GIT_ROOT/.gitversion" | grep "^version" | cut -f2 -d "=" | tr --delete " ")

# Build Deb package

pushd Debian

rm -rf ./OpenTAP
mkdir -p OpenTAP/DEBIAN
mkdir -p OpenTAP/usr/bin
mkdir -p OpenTAP/usr/share/tap
mkdir -p OpenTAP/usr/share/doc/tap
mkdir -p OpenTAP/var/log/SessionLogs

cp "$GIT_ROOT/LICENSE.txt" OpenTAP/usr/share/doc/tap/copyright

echo "Extracting OpenTAP"
unzip -q ../OpenTAP.TapPackage -d OpenTAP/usr/share/tap

pushd OpenTAP/usr/share/tap
chmod +x tap
ln -s ../../../var/log/SessionLogs
popd
pushd OpenTAP/usr/bin 
ln -s ../share/tap/tap
popd

echo "Computing package size"
BYTES=$(du -sb OpenTAP | cut -f1)
DIVISOR=1024

# Size in KB, rounded up -- addition and subtraction is necessary because we're using integer division
SIZE_KB=$(((BYTES - 1) / DIVISOR + 1)) 

# sed control-debian -e "s/@VERSION@/$VERSION/g" -e "s/@SIZE_KB@/$SIZE_KB/g" > OpenTAP/DEBIAN/control
sed control-debian -e "s/@SIZE_KB@/$SIZE_KB/g" > OpenTAP/DEBIAN/control
echo "Computing package version"
OpenTAP/usr/bin/tap sdk gitversion --replace OpenTAP/DEBIAN/control

chmod 775 OpenTAP/DEBIAN

echo "Building .deb package"
dpkg --build OpenTAP

mv OpenTAP.deb ..

echo "Built .deb package"
