#!/bin/bash

get_tap(){
    local tap_cmd="`which tap`"

    if [ ! -x "$tap_cmd" ]; then
        local tap_cmd="`which tap.exe`"
    fi

    printf "%q" "$tap_cmd"
}

quote_if_needed(){
    # Quote input if it contains spaces, otherwise return it as is
    awk '/ / { print "\""$0"\"" } /^[^ ]+$/ { print $0 }'
}

_tap_comp()
{
    _init_completion || return
    local current="${COMP_WORDS[COMP_CWORD]}"
    
    # Locally prevent OpenTAP from attaching the debugger, and from running in "isolated" mode 
    local WSLENV="TPM_PIPE=_prevent_tap_from_running_isolated_:OPENTAP_DEBUGGER_ASSEMBLY"
    declare -a words

    # skip tap.exe
    local words="${COMP_WORDS[@]:1}"

    mapfile -t completions < <( "$(get_tap)" "complete" "${words[@]}" )
    local MAGIC=( ${completions[@]:0:1} ); completions=( "${completions[@]:1}" )
    # local UNNAMED_ARGS=( ${completions[@]:0:1} ); completions=( "${completions[@]:1}" )

    if [[ ! "$MAGIC" == "BASH_COMPLETIONS_SUPPORTED"* ]]; then
       return 1
    fi

    local escaped_completions="$( printf '%q ' "${completions[@]}" )"

    case "${COMP_WORDS[@]}" in
        *"package create "*)
            _filedir '@(xml)'
            ;;
        *"package install "*)
            _filedir '@(TapPackage)'
            ;;
        *" run "*)
            _filedir '@(TapPlan)'
            ;;
    esac

    mapfile -t final_completions < <( compgen -W "$escaped_completions" -- "$current" | quote_if_needed )

    COMPREPLY+=("${final_completions[@]}")

}

if [[ "$(uname --kernel-version)" == *Microsoft* ]]; then
    complete -o nosort -F _tap_comp tap.exe
else
    complete -o nosort -F _tap_comp tap
fi